const DEFAULT_LANGUAGE_CODE = "en";

const rawLanguageData = [
  { code: "aa", locale: "aa-Latn-ET", name: "Afar" },
  { code: "ab", locale: "ab-Cyrl-GE", name: "Abkhazian" },
  { code: "ae", locale: "ae-Avst-IR", name: "Avestan" },
  { code: "af", locale: "af-Latn-ZA", name: "Afrikaans" },
  { code: "ak", locale: "ak-Latn-GH", name: "Akan" },
  { code: "am", locale: "am-Ethi-ET", name: "Amharic" },
  { code: "an", locale: "an-Latn-ES", name: "Aragonese" },
  { code: "ar", locale: "ar-Arab-EG", name: "Arabic" },
  { code: "as", locale: "as-Beng-IN", name: "Assamese" },
  { code: "av", locale: "av-Cyrl-RU", name: "Avaric" },
  { code: "ay", locale: "ay-Latn-BO", name: "Aymara" },
  { code: "az", locale: "az-Latn-AZ", name: "Azerbaijani" },
  { code: "ba", locale: "ba-Cyrl-RU", name: "Bashkir" },
  { code: "be", locale: "be-Cyrl-BY", name: "Belarusian" },
  { code: "bg", locale: "bg-Cyrl-BG", name: "Bulgarian" },
  { code: "bh", locale: "bho-Deva-IN", name: "Bihari languages" },
  { code: "bi", locale: "bi-Latn-VU", name: "Bislama" },
  { code: "bm", locale: "bm-Latn-ML", name: "Bambara" },
  { code: "bn", locale: "bn-Beng-BD", name: "Bengali" },
  { code: "bo", locale: "bo-Tibt-CN", name: "Tibetan" },
  { code: "br", locale: "br-Latn-FR", name: "Breton" },
  { code: "bs", locale: "bs-Latn-BA", name: "Bosnian" },
  { code: "ca", locale: "ca-Latn-ES", name: "Catalan" },
  { code: "ce", locale: "ce-Cyrl-RU", name: "Chechen" },
  { code: "ch", locale: "ch-Latn-GU", name: "Chamorro" },
  { code: "co", locale: "co-Latn-FR", name: "Corsican" },
  { code: "cr", locale: "cr-Cans-CA", name: "Cree" },
  { code: "cs", locale: "cs-Latn-CZ", name: "Czech" },
  { code: "cu", locale: "cu-Cyrl-RU", name: "Church Slavic" },
  { code: "cv", locale: "cv-Cyrl-RU", name: "Chuvash" },
  { code: "cy", locale: "cy-Latn-GB", name: "Welsh" },
  { code: "da", locale: "da-Latn-DK", name: "Danish" },
  { code: "de", locale: "de-Latn-DE", name: "German" },
  { code: "dv", locale: "dv-Thaa-MV", name: "Dhivehi" },
  { code: "dz", locale: "dz-Tibt-BT", name: "Dzongkha" },
  { code: "ee", locale: "ee-Latn-GH", name: "Ewe" },
  { code: "el", locale: "el-Grek-GR", name: "Modern Greek (1453-)" },
  { code: "en", locale: "en-Latn-US", name: "English" },
  { code: "eo", locale: "eo-Latn-001", name: "Esperanto" },
  { code: "es", locale: "es-Latn-ES", name: "Spanish" },
  { code: "et", locale: "et-Latn-EE", name: "Estonian" },
  { code: "eu", locale: "eu-Latn-ES", name: "Basque" },
  { code: "fa", locale: "fa-Arab-IR", name: "Persian" },
  { code: "ff", locale: "ff-Latn-SN", name: "Fulah" },
  { code: "fi", locale: "fi-Latn-FI", name: "Finnish" },
  { code: "fj", locale: "fj-Latn-FJ", name: "Fijian" },
  { code: "fo", locale: "fo-Latn-FO", name: "Faroese" },
  { code: "fr", locale: "fr-Latn-FR", name: "French" },
  { code: "fy", locale: "fy-Latn-NL", name: "Western Frisian" },
  { code: "ga", locale: "ga-Latn-IE", name: "Irish" },
  { code: "gd", locale: "gd-Latn-GB", name: "Scottish Gaelic" },
  { code: "gl", locale: "gl-Latn-ES", name: "Galician" },
  { code: "gn", locale: "gn-Latn-PY", name: "Guarani" },
  { code: "gu", locale: "gu-Gujr-IN", name: "Gujarati" },
  { code: "gv", locale: "gv-Latn-IM", name: "Manx" },
  { code: "ha", locale: "ha-Latn-NG", name: "Hausa" },
  { code: "he", locale: "he-Hebr-IL", name: "Hebrew" },
  { code: "hi", locale: "hi-Deva-IN", name: "Hindi" },
  { code: "ho", locale: "ho-Latn-PG", name: "Hiri Motu" },
  { code: "hr", locale: "hr-Latn-HR", name: "Croatian" },
  { code: "ht", locale: "ht-Latn-HT", name: "Haitian" },
  { code: "hu", locale: "hu-Latn-HU", name: "Hungarian" },
  { code: "hy", locale: "hy-Armn-AM", name: "Armenian" },
  { code: "hz", locale: "hz-Latn-NA", name: "Herero" },
  {
    code: "ia",
    locale: "ia-Latn-001",
    name: "Interlingua (International Auxiliary Language Association)",
  },
  { code: "id", locale: "id-Latn-ID", name: "Indonesian" },
  { code: "ie", locale: "ie-Latn-EE", name: "Interlingue" },
  { code: "ig", locale: "ig-Latn-NG", name: "Igbo" },
  { code: "ii", locale: "ii-Yiii-CN", name: "Sichuan Yi" },
  { code: "ik", locale: "ik-Latn-US", name: "Inupiaq" },
  { code: "io", locale: "io-Latn-001", name: "Ido" },
  { code: "is", locale: "is-Latn-IS", name: "Icelandic" },
  { code: "it", locale: "it-Latn-IT", name: "Italian" },
  { code: "iu", locale: "iu-Cans-CA", name: "Inuktitut" },
  { code: "ja", locale: "ja-Jpan-JP", name: "Japanese" },
  { code: "jv", locale: "jv-Latn-ID", name: "Javanese" },
  { code: "ka", locale: "ka-Geor-GE", name: "Georgian" },
  { code: "kg", locale: "kg-Latn-CD", name: "Kongo" },
  { code: "ki", locale: "ki-Latn-KE", name: "Kikuyu" },
  { code: "kj", locale: "kj-Latn-NA", name: "Kuanyama" },
  { code: "kk", locale: "kk-Cyrl-KZ", name: "Kazakh" },
  { code: "kl", locale: "kl-Latn-GL", name: "Kalaallisut" },
  { code: "km", locale: "km-Khmr-KH", name: "Khmer" },
  { code: "kn", locale: "kn-Knda-IN", name: "Kannada" },
  { code: "ko", locale: "ko-Kore-KR", name: "Korean" },
  { code: "kr", locale: "kr-Latn-NG", name: "Kanuri" },
  { code: "ks", locale: "ks-Arab-IN", name: "Kashmiri" },
  { code: "ku", locale: "ku-Latn-TR", name: "Kurdish" },
  { code: "kv", locale: "kv-Cyrl-RU", name: "Komi" },
  { code: "kw", locale: "kw-Latn-GB", name: "Cornish" },
  { code: "ky", locale: "ky-Cyrl-KG", name: "Kirghiz" },
  { code: "la", locale: "la-Latn-VA", name: "Latin" },
  { code: "lb", locale: "lb-Latn-LU", name: "Luxembourgish" },
  { code: "lg", locale: "lg-Latn-UG", name: "Ganda" },
  { code: "li", locale: "li-Latn-NL", name: "Limburgan" },
  { code: "ln", locale: "ln-Latn-CD", name: "Lingala" },
  { code: "lo", locale: "lo-Laoo-LA", name: "Lao" },
  { code: "lt", locale: "lt-Latn-LT", name: "Lithuanian" },
  { code: "lu", locale: "lu-Latn-CD", name: "Luba-Katanga" },
  { code: "lv", locale: "lv-Latn-LV", name: "Latvian" },
  { code: "mg", locale: "mg-Latn-MG", name: "Malagasy" },
  { code: "mh", locale: "mh-Latn-MH", name: "Marshallese" },
  { code: "mi", locale: "mi-Latn-NZ", name: "Maori" },
  { code: "mk", locale: "mk-Cyrl-MK", name: "Macedonian" },
  { code: "ml", locale: "ml-Mlym-IN", name: "Malayalam" },
  { code: "mn", locale: "mn-Cyrl-MN", name: "Mongolian" },
  { code: "mr", locale: "mr-Deva-IN", name: "Marathi" },
  {
    code: "ms",
    locale: "ms-Latn-MY",
    name: "Malay (macrolanguage)",
  },
  { code: "mt", locale: "mt-Latn-MT", name: "Maltese" },
  { code: "my", locale: "my-Mymr-MM", name: "Burmese" },
  { code: "na", locale: "na-Latn-NR", name: "Nauru" },
  { code: "nb", locale: "nb-Latn-NO", name: "Norwegian Bokmål" },
  { code: "nd", locale: "nd-Latn-ZW", name: "North Ndebele" },
  {
    code: "ne",
    locale: "ne-Deva-NP",
    name: "Nepali (macrolanguage)",
  },
  { code: "ng", locale: "ng-Latn-NA", name: "Ndonga" },
  { code: "nl", locale: "nl-Latn-NL", name: "Dutch" },
  { code: "nn", locale: "nn-Latn-NO", name: "Norwegian Nynorsk" },
  { code: "no", locale: "no-Latn-NO", name: "Norwegian" },
  { code: "nr", locale: "nr-Latn-ZA", name: "South Ndebele" },
  { code: "nv", locale: "nv-Latn-US", name: "Navajo" },
  { code: "ny", locale: "ny-Latn-MW", name: "Chichewa" },
  {
    code: "oc",
    locale: "oc-Latn-FR",
    name: "Occitan (post 1500)",
  },
  { code: "oj", locale: "oj-Cans-CA", name: "Ojibwa" },
  { code: "om", locale: "om-Latn-ET", name: "Oromo" },
  {
    code: "or",
    locale: "or-Orya-IN",
    name: "Oriya (macrolanguage)",
  },
  { code: "os", locale: "os-Cyrl-GE", name: "Iron Ossetic" },
  { code: "pa", locale: "pa-Guru-IN", name: "Panjabi" },
  { code: "pi", locale: "pi-Sinh-IN", name: "Pali" },
  { code: "pl", locale: "pl-Latn-PL", name: "Polish" },
  { code: "ps", locale: "ps-Arab-AF", name: "Pushto" },
  { code: "pt", locale: "pt-Latn-BR", name: "Portuguese" },
  { code: "qu", locale: "qu-Latn-PE", name: "Quechua" },
  { code: "rm", locale: "rm-Latn-CH", name: "Romansh" },
  { code: "rn", locale: "rn-Latn-BI", name: "Rundi" },
  { code: "ro", locale: "ro-Latn-RO", name: "Romanian" },
  { code: "ru", locale: "ru-Cyrl-RU", name: "Russian" },
  { code: "rw", locale: "rw-Latn-RW", name: "Kinyarwanda" },
  { code: "sa", locale: "sa-Deva-IN", name: "Sanskrit" },
  { code: "sc", locale: "sc-Latn-IT", name: "Sardinian" },
  { code: "sd", locale: "sd-Arab-PK", name: "Sindhi" },
  { code: "se", locale: "se-Latn-NO", name: "Northern Sami" },
  { code: "sg", locale: "sg-Latn-CF", name: "Sango" },
  { code: "sh", locale: "sr-Latn-RS", name: "Serbo-Croatian" },
  { code: "si", locale: "si-Sinh-LK", name: "Sinhala" },
  { code: "sk", locale: "sk-Latn-SK", name: "Slovak" },
  { code: "sl", locale: "sl-Latn-SI", name: "Slovenian" },
  { code: "sm", locale: "sm-Latn-WS", name: "Samoan" },
  { code: "sn", locale: "sn-Latn-ZW", name: "Shona" },
  { code: "so", locale: "so-Latn-SO", name: "Somali" },
  { code: "sq", locale: "sq-Latn-AL", name: "Albanian" },
  { code: "sr", locale: "sr-Cyrl-RS", name: "Serbian" },
  { code: "ss", locale: "ss-Latn-ZA", name: "Swati" },
  { code: "st", locale: "st-Latn-ZA", name: "Southern Sotho" },
  { code: "su", locale: "su-Latn-ID", name: "Sundanese" },
  { code: "sv", locale: "sv-Latn-SE", name: "Swedish" },
  {
    code: "sw",
    locale: "sw-Latn-TZ",
    name: "Swahili (macrolanguage)",
  },
  { code: "ta", locale: "ta-Taml-IN", name: "Tamil" },
  { code: "te", locale: "te-Telu-IN", name: "Telugu" },
  { code: "tg", locale: "tg-Cyrl-TJ", name: "Tajik" },
  { code: "th", locale: "th-Thai-TH", name: "Thai" },
  { code: "ti", locale: "ti-Ethi-ET", name: "Tigrinya" },
  { code: "tk", locale: "tk-Latn-TM", name: "Turkmen" },
  { code: "tl", locale: "fil-Latn-PH", name: "Tagalog" },
  { code: "tn", locale: "tn-Latn-ZA", name: "Tswana" },
  {
    code: "to",
    locale: "to-Latn-TO",
    name: "Tonga (Tonga Islands)",
  },
  { code: "tr", locale: "tr-Latn-TR", name: "Turkish" },
  { code: "ts", locale: "ts-Latn-ZA", name: "Tsonga" },
  { code: "tt", locale: "tt-Cyrl-RU", name: "Tatar" },
  { code: "tw", locale: "tw", name: "Twi" },
  { code: "ty", locale: "ty-Latn-PF", name: "Tahitian" },
  { code: "ug", locale: "ug-Arab-CN", name: "Uighur" },
  { code: "uk", locale: "uk-Cyrl-UA", name: "Ukrainian" },
  { code: "ur", locale: "ur-Arab-PK", name: "Urdu" },
  { code: "uz", locale: "uz-Latn-UZ", name: "Uzbek" },
  { code: "ve", locale: "ve-Latn-ZA", name: "Venda" },
  { code: "vi", locale: "vi-Latn-VN", name: "Vietnamese" },
  { code: "vo", locale: "vo-Latn-001", name: "Volapük" },
  { code: "wa", locale: "wa-Latn-BE", name: "Walloon" },
  { code: "wo", locale: "wo-Latn-SN", name: "Wolof" },
  { code: "xh", locale: "xh-Latn-ZA", name: "Xhosa" },
  { code: "yi", locale: "yi-Hebr-UA", name: "Yiddish" },
  { code: "yo", locale: "yo-Latn-NG", name: "Yoruba" },
  { code: "za", locale: "za-Latn-CN", name: "Zhuang" },
  { code: "zh", locale: "zh-Hans-CN", name: "Chinese" },
  { code: "zu", locale: "zu-Latn-ZA", name: "Zulu" },
];

const orderedLanguageData = [
  ...rawLanguageData.filter(({ code }) => code === DEFAULT_LANGUAGE_CODE),
  ...rawLanguageData.filter(({ code }) => code !== DEFAULT_LANGUAGE_CODE),
];

export const languageData = orderedLanguageData;
