export const ACCESS_TOKEN_EXPIRES_IN_SECONDS = 15 * 60;
export const REFRESH_TOKEN_EXPIRES_IN_DAYS = 30;
export const EMAIL_VERIFICATION_EXPIRES_IN_MINUTES = 60;
export const PASSWORD_RESET_EXPIRES_IN_MINUTES = 60;
